# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Změnit řazení projektů

# Attribute name
nameFrom: title

# Model Class name
modelClass: Jagu\KrupaArchitekti\Models\Project

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
